versions:
  "0.0.1":
    folder: all
  "0.0.2":
    folder: all
  "0.0.3":
    folder: all
  "0.0.4":
    folder: all
  "0.0.5":
    folder: all
  "0.0.6":
    folder: all
  "0.0.7":
    folder: all
  "0.0.8":
    folder: all